### ISSUE TITLE
Not able to finish script: /etc/rancher/k3s/k3s.yaml: permission denied

### ISSUE THREAD

**Issue by DJIronic** [MrSimonEmms/gitpod-k3s-guide#25]
Hello,

I tried to install via this script. Firstly I used Ubuntu 22.04 and had this issue, then I tried Ubuntu 20.04 as that was a version I was able to use this script in the past.

No I am ending on:

```
WARN[0000] Unable to read /etc/rancher/k3s/k3s.yaml, please start server with --write-kubeconfig-mode to modify kube config permissions 
error: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
```

and have no idea, how to fix this. I event tried to google the issue, but no solution (like [this](https://0to1.nl/post/k3s-kubectl-permission/) ) did not work, but only poushed be to error:

`error: no context exists with the name: "gitpod-k3s"`

Here is my whole log with server IP redacted: https://paste.brcb.eu/jymuzuboti.sql

I tried everything I was able to find or debug by myself, but now I am at the end of my capabilities.

Thank you for your help!

**Comment by mrsimonemms** [comment]
Hey @DJIronic - what version of `k3sup` are you using? I've seen this in the past and remember that there was a recently released fix for Ubuntu 22.04. My guess is that you're using an old version which will be solved if you update the version

**Comment by DJIronic** [comment]
Hello,

I just installed it  via: 
```
curl -sLS https://get.k3sup.dev | sh
sudo install k3sup /usr/local/bin/
```

As I found on their GitHub page.


```
simonc@gitpod:~$ k3sup version
 _    _____                 
| | _|___ / ___ _   _ _ __  
| |/ / |_ \/ __| | | | '_ \ 
|   < ___) \__ \ |_| | |_) |
|_|\_\____/|___/\__,_| .__/ 
                     |_|    

bootstrap K3s over SSH in < 60s 🚀
🐳 k3sup needs your support: https://github.com/sponsors/alexellis

Version: 0.12.7
Git Commit: e3ff08cf1d3798c7d89372f30a79b5fd4a1d2500
simonc@gitpod:~$ 
```

**Comment by mrsimonemms** [comment]
That's actually a later version than I'm using.

What cloud are you deploying to? You need a machine with passwordless sudo

**Comment by DJIronic** [comment]
Am I deploying to a clear Ubuntu VM I installed on VMware ESXi. Yes, passwordless sudo was setup on both 20.04 and 22.04 systems I tried the install on.

**Comment by DJIronic** [comment]
I am currently installing absolutely clear Ubuntu servr 22.04 and I will create a snapshot after setting up the passwordless sudo. So we can fastly debug the situation without reinstalls.

PS: We are also on Gitpod Github, so if you want, we can discuss there, I can also let you access the server if its something that helps you.

**Comment by mrsimonemms** [comment]
I wonder if [this](https://devops.stackexchange.com/questions/16043/error-error-loading-config-file-etc-rancher-k3s-k3s-yaml-open-etc-rancher) is the same problem?

**Comment by DJIronic** [comment]
Error looks the same.

**Comment by DJIronic** [comment]
OK, I tried to do a stupid fix when I added sudo before all kubectl commands :) 

and the result is:
`error: no context exists with the name: "gitpod-k3s"`

**Comment by mrsimonemms** [comment]
Rather than changing everything so it starts with `sudo`, can you run the script with `sudo`?

**Comment by DJIronic** [comment]
For some reason, that did not work. Even when run with sudo or with root user set as the one running it.

I was able to install it with help of a Discord user that made this edit of the script: https://pastebin.com/raw/afbnu9g5

Then I changed kubectl to sudo kubectl and then it worked and I was able to install Gitpod and het it working correctly.

**Comment by mrsimonemms** [comment]
Looks like it only removed the `--context` flag on the `k3sup` command - no idea why that was important, but that'll likely be something in that project.

Glad you're sorted now
