### ISSUE TITLE
make the name of private key of cloudflare more clear.

### ISSUE THREAD

**Issue by jgao1025** [MrSimonEmms/gitpod-k3s-guide#27]
In .env.example, it said to use 

`CLOUDFLARE_API_KEY`

cloudflare does have a global api key, however, it won't work if I put in the settings.

The right way is to generate an api token with permissions as Zone.Zone, Zone.DNS and then put the token in the setting. No big issue here, just think if this can be more clear then it would be better.

`https://github.com/MrSimonEmms/gitpod-k3s-guide/blob/main/.env.example#L23`

**Comment by mrsimonemms** [comment]
PRs welcome - probably worth updating in the README
